// components/CVTab.tsx - Resume builder + ATS optimizer (My CV tab)
"use client";

import { useMemo, useState } from "react";
import type { Resume, TemplateId } from "@/lib/types";
import { analyzeResume } from "@/lib/atsAnalyzer";
import { generateResumeHtml, TEMPLATE_OPTIONS } from "@/lib/resumeTemplates";
import { getKeywordOptions, getSkillOptions, loadRoleKeywords } from "@/lib/roleKeywords";
import { getProjectNames, getProjectByName } from "@/lib/projectsDb";
import { toDateInputValue, safeFileName } from "@/lib/resumeUtils";
import { getAccessToken } from "@/lib/supabaseClient";
import KeywordInput from "./KeywordInput";
import AtsAudit from "./AtsAudit";
import ResumePreview, { printResume } from "./ResumePreview";

interface Props {
  resume: Resume;
  onResumeChange: (r: Resume) => void;
  targetRole: string;
  notify: (text: string) => void;
}

type Note = { kind: "success" | "error" | "warning"; text: string } | null;

export default function CVTab({ resume, onResumeChange, targetRole, notify }: Props) {
  const [rightTab, setRightTab] = useState<"preview" | "audit">("preview");
  const [templateId, setTemplateId] = useState<TemplateId>("modern");
  const [summaryBusy, setSummaryBusy] = useState(false);
  const [expBusy, setExpBusy] = useState(false);
  const [note, setNote] = useState<Note>(null);

  // AI experience generator inputs
  const [aiRole, setAiRole] = useState("");
  const [aiDomain, setAiDomain] = useState("");
  const [aiYears, setAiYears] = useState("");
  const [aiDaily, setAiDaily] = useState("");
  const [aiTools, setAiTools] = useState("");
  const [aiClient, setAiClient] = useState("");
  const [aiLocation, setAiLocation] = useState("");
  const [aiStartDate, setAiStartDate] = useState("");
  const [aiEndDate, setAiEndDate] = useState("");
  const [aiPresent, setAiPresent] = useState(false);
  const [presetSelect, setPresetSelect] = useState("");
  const [certPreset, setCertPreset] = useState("");

  const report = useMemo(() => analyzeResume(resume, targetRole), [resume, targetRole]);
  const keywordOptions = useMemo(() => getKeywordOptions(targetRole), [targetRole]);
  const skillOptions = useMemo(() => getSkillOptions(targetRole), [targetRole]);
  const roleTitle = loadRoleKeywords()[targetRole]?.title || "Role";

  const patch = (fn: (draft: Resume) => void) => {
    const next: Resume = structuredClone(resume);
    fn(next);
    onResumeChange(next);
  };

  const score = report.score;
  const previewHtml = generateResumeHtml(resume, templateId);
  const fileName = `${safeFileName(resume.personal.fullName)}_resume.pdf`;

  // ── AI: professional summary ──
  const generateSummary = async () => {
    setSummaryBusy(true);
    setNote(null);
    try {
      const token = await getAccessToken();
      if (!token) {
        setNote({ kind: "error", text: "Please sign in to use AI generation." });
        setSummaryBusy(false);
        return;
      }
      const res = await fetch("/api/generate-summary", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          profile_statement: resume.summary,
          personal: resume.personal,
          experience: resume.experience,
          education: resume.education,
          projects: resume.projects,
          skills: resume.skills,
          target_role: targetRole,
        }),
      });
      const data = await res.json();
      if (data.summary) {
        patch((d) => {
          d.summary = data.summary;
        });
        setNote(
          data.api_used
            ? { kind: "success", text: "Professional summary generated by OpenAI." }
            : {
                kind: "warning",
                text: `Fallback summary generated; AI unavailable${
                  data.api_error ? ` — ${data.api_error}` : ""
                }.`,
              }
        );
      } else {
        setNote({ kind: "error", text: "Could not generate a professional summary." });
      }
    } catch (e) {
      setNote({ kind: "error", text: `Generation failed: ${e instanceof Error ? e.message : e}` });
    } finally {
      setSummaryBusy(false);
    }
  };

  // ── AI: experience entry ──
  const generateExperienceEntry = async () => {
    setExpBusy(true);
    setNote(null);
    const entryInfo = {
      company: aiClient || "Generated Project",
      role: aiRole || resume.personal.headline || "",
      domain: aiDomain,
      client: aiClient,
      details: aiDaily,
      tools: aiTools,
      years: aiYears,
      target_role: targetRole,
    };
    try {
      const token = await getAccessToken();
      if (!token) {
        setNote({ kind: "error", text: "Please sign in to use AI generation." });
        setExpBusy(false);
        return;
      }
      const res = await fetch("/api/generate-bullets", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(entryInfo),
      });
      const data = await res.json();
      const bullets: string[] = data.bullets || [];
      const endDateValue = aiPresent ? "Present" : aiEndDate;
      patch((d) => {
        d.experience.push({
          company: entryInfo.company,
          role: entryInfo.role,
          location: aiLocation,
          startDate: aiStartDate,
          endDate: endDateValue,
          bullets,
        });
      });
      // Clear the generator inputs so the next entry starts fresh
      setAiRole("");
      setAiDomain("");
      setAiYears("");
      setAiDaily("");
      setAiTools("");
      setAiClient("");
      setAiLocation("");
      setAiStartDate("");
      setAiEndDate("");
      setAiPresent(false);
      setNote(
        data.api_used
          ? { kind: "success", text: "Experience entry added below." }
          : {
              kind: "warning",
              text: `Fallback bullets generated; AI unavailable${
                data.api_error ? ` — ${data.api_error}` : ""
              }.`,
            }
      );
    } catch (e) {
      setNote({ kind: "error", text: `AI generation failed: ${e instanceof Error ? e.message : e}` });
    } finally {
      setExpBusy(false);
    }
  };

  const addPresetProject = () => {
    if (!presetSelect) return;
    const preset = getProjectByName(presetSelect);
    if (!preset) return;
    const exists = resume.projects.some((p) => p.name === preset.name);
    if (exists) {
      notify("This project is already in your resume.");
      return;
    }
    patch((d) => {
      d.projects.push({
        name: preset.name,
        tech: preset.tech,
        link: preset.link,
        description: preset.description,
      });
    });
    notify(`Added: ${preset.name.slice(0, 50)}...`);
    setPresetSelect("");
  };

  return (
    <div>
      {/* Top score banner */}
      <h3>🎯 ATS Optimization Score</h3>
      <div style={{ display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap" }}>
        <div className="metric">
          <div className="metric-label">Current score</div>
          <div className="metric-value">{score} / 100</div>
        </div>
        <div style={{ flex: 1, minWidth: 240 }}>
          {score >= 75 ? (
            <div className="alert alert-success">Strong ATS match — keep refining!</div>
          ) : score >= 50 ? (
            <div className="alert alert-warning">Moderate match — add more role keywords.</div>
          ) : (
            <div className="alert alert-error">
              Weak match — increase keywords and section completeness.
            </div>
          )}
        </div>
      </div>

      {note && <div className={`alert alert-${note.kind}`}>{note.text}</div>}

      <div className="cv-layout" style={{ marginTop: 16 }}>
        {/* LEFT: editor */}
        <div>
          <h3>Resume Editor — {roleTitle}</h3>

          {/* Personal */}
          <details className="expander" open>
            <summary>👤 Personal Details</summary>
            <div className="expander-body">
              <label className="field-label">Full Name</label>
              <input
                value={resume.personal.fullName}
                onChange={(e) => patch((d) => (d.personal.fullName = e.target.value))}
              />
              <label className="field-label">Professional Headline</label>
              <input
                value={resume.personal.headline}
                placeholder="Data Engineer | Data Pipelines | ETL Processes"
                onChange={(e) => patch((d) => (d.personal.headline = e.target.value))}
              />
              <div className="grid-2">
                <div>
                  <label className="field-label">Email</label>
                  <input
                    value={resume.personal.email}
                    onChange={(e) => patch((d) => (d.personal.email = e.target.value))}
                  />
                </div>
                <div>
                  <label className="field-label">Phone</label>
                  <input
                    value={resume.personal.phone}
                    onChange={(e) => patch((d) => (d.personal.phone = e.target.value))}
                  />
                </div>
              </div>
              <label className="field-label">Location</label>
              <input
                value={resume.personal.location}
                onChange={(e) => patch((d) => (d.personal.location = e.target.value))}
              />
              <div className="grid-2">
                <div>
                  <label className="field-label">LinkedIn</label>
                  <input
                    value={resume.personal.linkedin}
                    onChange={(e) => patch((d) => (d.personal.linkedin = e.target.value))}
                  />
                </div>
                <div>
                  <label className="field-label">GitHub</label>
                  <input
                    value={resume.personal.github}
                    onChange={(e) => patch((d) => (d.personal.github = e.target.value))}
                  />
                </div>
              </div>
              <label className="field-label">Portfolio / Website</label>
              <input
                value={resume.personal.website}
                onChange={(e) => patch((d) => (d.personal.website = e.target.value))}
              />
            </div>
          </details>

          {/* Experience */}
          <details className="expander">
            <summary>💼 Work / Internship Experience</summary>
            <div className="expander-body">
              <h4>✨ AI Experience Generator</h4>
              <p className="caption">
                Provide concise details and click Generate Experience to create ATS-friendly bullets
                for one experience entry.
              </p>
              <div className="grid-2">
                <div>
                  <label className="field-label">Current Role:</label>
                  <input value={aiRole} onChange={(e) => setAiRole(e.target.value)} />
                  <label className="field-label">Industry / Domain:</label>
                  <input
                    value={aiDomain}
                    placeholder="e.g. Retail, Healthcare, Banking"
                    onChange={(e) => setAiDomain(e.target.value)}
                  />
                  <label className="field-label">Years of Experience:</label>
                  <input value={aiYears} onChange={(e) => setAiYears(e.target.value)} />
                </div>
                <div>
                  <label className="field-label">Daily Activities (short):</label>
                  <textarea
                    rows={3}
                    value={aiDaily}
                    placeholder="What you do day-to-day (brief)"
                    onChange={(e) => setAiDaily(e.target.value)}
                  />
                  <KeywordInput
                    label="Tools I Actually Use:"
                    value={aiTools}
                    options={keywordOptions}
                    placeholder="e.g. PySpark, Databricks, Azure Data Factory"
                    onChange={setAiTools}
                  />
                  <label className="field-label">Client Name (optional):</label>
                  <input
                    value={aiClient}
                    placeholder="Optional client or project name"
                    onChange={(e) => setAiClient(e.target.value)}
                  />
                </div>
              </div>

              {/* Location + duration — applied to the generated entry */}
              <div className="grid-2" style={{ marginTop: 8 }}>
                <div>
                  <label className="field-label">Location:</label>
                  <input
                    value={aiLocation}
                    placeholder="e.g. Bengaluru, India / Remote"
                    onChange={(e) => setAiLocation(e.target.value)}
                  />
                </div>
                <div className="grid-2">
                  <div>
                    <label className="field-label">Start Date</label>
                    <input
                      type="date"
                      value={toDateInputValue(aiStartDate)}
                      onChange={(e) => setAiStartDate(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="field-label">End Date</label>
                    <label style={{ display: "block", fontSize: "0.8rem", cursor: "pointer" }}>
                      <input
                        type="checkbox"
                        checked={aiPresent}
                        style={{ width: "auto", marginRight: 4 }}
                        onChange={(e) => setAiPresent(e.target.checked)}
                      />
                      Present
                    </label>
                    {!aiPresent && (
                      <input
                        type="date"
                        value={toDateInputValue(aiEndDate)}
                        onChange={(e) => setAiEndDate(e.target.value)}
                      />
                    )}
                  </div>
                </div>
              </div>

              <button className="btn-cta full" onClick={generateExperienceEntry} disabled={expBusy} style={{ marginTop: 8 }}>
                {expBusy && <span className="spinner" />}Generate &amp; Add Experience
              </button>

              <hr />

              {resume.experience.map((exp, i) => (
                <div key={i}>
                  <strong>Entry {i + 1}</strong>
                  <div className="grid-2">
                    <div>
                      <label className="field-label">Company</label>
                      <input
                        value={exp.company}
                        onChange={(e) =>
                          patch((d) => (d.experience[i].company = e.target.value))
                        }
                      />
                    </div>
                    <div>
                      <label className="field-label">Location</label>
                      <input
                        value={exp.location}
                        onChange={(e) =>
                          patch((d) => (d.experience[i].location = e.target.value))
                        }
                      />
                    </div>
                  </div>
                  <div className="grid-2">
                    <div>
                      <label className="field-label">Role/Title</label>
                      <input
                        value={exp.role}
                        onChange={(e) => patch((d) => (d.experience[i].role = e.target.value))}
                      />
                    </div>
                    <div className="grid-2">
                      <div>
                        <label className="field-label">Start</label>
                        <input
                          type="date"
                          value={toDateInputValue(exp.startDate)}
                          onChange={(e) =>
                            patch((d) => (d.experience[i].startDate = e.target.value))
                          }
                        />
                      </div>
                      <div>
                        <label className="field-label">End</label>
                        <label style={{ display: "block", fontSize: "0.8rem", cursor: "pointer" }}>
                          <input
                            type="checkbox"
                            checked={exp.endDate.trim().toLowerCase() === "present"}
                            style={{ width: "auto", marginRight: 4 }}
                            onChange={(e) =>
                              patch(
                                (d) =>
                                  (d.experience[i].endDate = e.target.checked ? "Present" : "")
                              )
                            }
                          />
                          Present
                        </label>
                        {exp.endDate.trim().toLowerCase() !== "present" && (
                          <input
                            type="date"
                            value={toDateInputValue(exp.endDate)}
                            onChange={(e) =>
                              patch((d) => (d.experience[i].endDate = e.target.value))
                            }
                          />
                        )}
                      </div>
                    </div>
                  </div>
                  <label className="field-label">Bullet points (use action verbs + metrics)</label>
                  {exp.bullets.map((b, bi) => (
                    <div className="bullet-row" key={bi}>
                      <input
                        value={b}
                        placeholder="Engineered a data pipeline that reduced latency by 40%..."
                        onChange={(e) =>
                          patch((d) => (d.experience[i].bullets[bi] = e.target.value))
                        }
                      />
                      <button
                        className="icon-btn"
                        onClick={() => patch((d) => d.experience[i].bullets.splice(bi, 1))}
                      >
                        ✖
                      </button>
                    </div>
                  ))}
                  <div className="btn-row" style={{ marginTop: 6 }}>
                    <button onClick={() => patch((d) => d.experience[i].bullets.push(""))}>
                      + Bullet
                    </button>
                    <button onClick={() => patch((d) => d.experience.splice(i, 1))}>
                      🗑 Delete Entry
                    </button>
                  </div>
                  <hr />
                </div>
              ))}

              <button
                className="full"
                onClick={() =>
                  patch((d) =>
                    d.experience.push({
                      company: "",
                      role: "",
                      location: "",
                      startDate: "",
                      endDate: "",
                      bullets: [""],
                    })
                  )
                }
              >
                + Add More Experience
              </button>
            </div>
          </details>

          {/* Education */}
          <details className="expander">
            <summary>🎓 Education</summary>
            <div className="expander-body">
              {resume.education.map((edu, i) => {
                const parts = String(edu.date || "").split(" to ");
                return (
                  <div key={i}>
                    <div className="grid-2">
                      <div>
                        <label className="field-label">School</label>
                        <input
                          value={edu.school}
                          onChange={(e) =>
                            patch((d) => (d.education[i].school = e.target.value))
                          }
                        />
                      </div>
                      <div>
                        <label className="field-label">Degree</label>
                        <input
                          value={edu.degree}
                          onChange={(e) =>
                            patch((d) => (d.education[i].degree = e.target.value))
                          }
                        />
                      </div>
                    </div>
                    <div className="grid-2">
                      <div>
                        <label className="field-label">Location</label>
                        <input
                          value={edu.location}
                          onChange={(e) =>
                            patch((d) => (d.education[i].location = e.target.value))
                          }
                        />
                      </div>
                      <div className="grid-2">
                        <div>
                          <label className="field-label">Start Date</label>
                          <input
                            type="date"
                            value={toDateInputValue(parts[0])}
                            onChange={(e) =>
                              patch(
                                (d) =>
                                  (d.education[i].date = `${e.target.value} to ${
                                    toDateInputValue(parts[parts.length - 1]) || ""
                                  }`)
                              )
                            }
                          />
                        </div>
                        <div>
                          <label className="field-label">End Date</label>
                          <input
                            type="date"
                            value={toDateInputValue(parts[parts.length - 1])}
                            onChange={(e) =>
                              patch(
                                (d) =>
                                  (d.education[i].date = `${
                                    toDateInputValue(parts[0]) || ""
                                  } to ${e.target.value}`)
                              )
                            }
                          />
                        </div>
                      </div>
                    </div>
                    <label className="field-label">Details (GPA, Honors)</label>
                    <input
                      value={edu.details}
                      onChange={(e) => patch((d) => (d.education[i].details = e.target.value))}
                    />
                    <button
                      style={{ marginTop: 8 }}
                      onClick={() => patch((d) => d.education.splice(i, 1))}
                    >
                      🗑 Delete
                    </button>
                    <hr />
                  </div>
                );
              })}
              <button
                className="full"
                onClick={() =>
                  patch((d) =>
                    d.education.push({
                      school: "",
                      degree: "",
                      location: "",
                      date: "",
                      details: "",
                    })
                  )
                }
              >
                + Add Education
              </button>
            </div>
          </details>

          {/* Projects */}
          <details className="expander">
            <summary>💻 Projects</summary>
            <div className="expander-body">
              <label className="field-label">➕ Add from preset</label>
              <select value={presetSelect} onChange={(e) => setPresetSelect(e.target.value)}>
                <option value="">— select a preset project —</option>
                {getProjectNames().map((name) => (
                  <option key={name} value={name}>
                    {name}
                  </option>
                ))}
              </select>
              {presetSelect && (
                <button className="primary full" style={{ marginTop: 8 }} onClick={addPresetProject}>
                  Add Selected Project
                </button>
              )}
              <hr />
              {resume.projects.map((proj, i) => (
                <div key={i}>
                  <div className="grid-2">
                    <div>
                      <label className="field-label">Project Name</label>
                      <input
                        value={proj.name}
                        onChange={(e) => patch((d) => (d.projects[i].name = e.target.value))}
                      />
                    </div>
                    <div>
                      <KeywordInput
                        label="Tech Stack"
                        value={proj.tech}
                        options={keywordOptions}
                        placeholder="e.g. Python, SQL, Power BI"
                        onChange={(v) => patch((d) => (d.projects[i].tech = v))}
                      />
                    </div>
                  </div>
                  <label className="field-label">Link</label>
                  <input
                    value={proj.link}
                    onChange={(e) => patch((d) => (d.projects[i].link = e.target.value))}
                  />
                  <label className="field-label">Description</label>
                  <textarea
                    rows={4}
                    value={proj.description}
                    onChange={(e) => patch((d) => (d.projects[i].description = e.target.value))}
                  />
                  <button
                    style={{ marginTop: 8 }}
                    onClick={() => patch((d) => d.projects.splice(i, 1))}
                  >
                    🗑 Delete
                  </button>
                  <hr />
                </div>
              ))}
              <button
                className="full"
                onClick={() =>
                  patch((d) =>
                    d.projects.push({ name: "", tech: "", link: "", description: "" })
                  )
                }
              >
                + Add Blank Project
              </button>
            </div>
          </details>

          {/* Skills */}
          <details className="expander">
            <summary>🛠 Skills</summary>
            <div className="expander-body">
              {resume.skills.map((s, i) => (
                <div key={i}>
                  <label className="field-label">Group Name</label>
                  <input
                    value={s.category}
                    onChange={(e) => patch((d) => (d.skills[i].category = e.target.value))}
                  />
                  <KeywordInput
                    label="Skills"
                    value={s.list}
                    options={skillOptions}
                    placeholder="Add custom skills separated by commas"
                    onChange={(v) => patch((d) => (d.skills[i].list = v))}
                  />
                  <button
                    style={{ marginTop: 8 }}
                    onClick={() => patch((d) => d.skills.splice(i, 1))}
                  >
                    🗑 Delete
                  </button>
                  <hr />
                </div>
              ))}
              <button
                className="full"
                onClick={() => patch((d) => d.skills.push({ category: "", list: "" }))}
              >
                + Add Skill Group
              </button>
            </div>
          </details>

          {/* Certifications */}
          <details className="expander">
            <summary>📜 Certifications</summary>
            <div className="expander-body">
              <label className="field-label">➕ Add from preset</label>
              <select value={certPreset} onChange={(e) => setCertPreset(e.target.value)}>
                <option value="">— select a certification —</option>
                <option value="Data Science With Big Data Engineering + GenAI">Data Science With Big Data Engineering + GenAI</option>
                <option value="Data Analytics with Power BI">Data Analytics with Power BI</option>
                <option value="Microsoft Azure Data Fundamentals DP-900">Microsoft Azure Data Fundamentals DP-900</option>
              </select>
              {certPreset && (
                <button
                  className="primary full"
                  style={{ marginTop: 8 }}
                  onClick={() => {
                    const exists = resume.certifications.some((c) => c.name === certPreset);
                    if (exists) {
                      notify("This certification is already in your resume.");
                    } else {
                      patch((d) =>
                        d.certifications.push({
                          name: certPreset,
                          issuer: "",
                          date: "",
                        })
                      );
                      notify(`Added: ${certPreset}`);
                    }
                    setCertPreset("");
                  }}
                >
                  Add Selected Certification
                </button>
              )}
              <hr />
              {resume.certifications.map((c, i) => (
                <div key={i}>
                  <label className="field-label">Title</label>
                  <input
                    value={c.name}
                    onChange={(e) => patch((d) => (d.certifications[i].name = e.target.value))}
                  />
                  <button
                    style={{ marginTop: 8 }}
                    onClick={() => patch((d) => d.certifications.splice(i, 1))}
                  >
                    🗑 Delete
                  </button>
                  <hr />
                </div>
              ))}
              <button
                className="full"
                onClick={() =>
                  patch((d) => d.certifications.push({ name: "", issuer: "", date: "" }))
                }
              >
                + Add Certification
              </button>
            </div>
          </details>

          {/* Professional Summary — generated last so it reflects the full resume */}
          <details className="expander" open>
            <summary>✍ Professional Summary</summary>
            <div className="expander-body">
              <p className="caption" style={{ marginTop: 0 }}>
                Generate this last — it&apos;s written from everything you&apos;ve added above
                (experience, education, projects, skills).
              </p>
              <label className="field-label">Profile Statement</label>
              <textarea
                rows={4}
                value={resume.summary}
                placeholder="Highlight your data science expertise, tools you use, and quantified achievements..."
                onChange={(e) => patch((d) => (d.summary = e.target.value))}
              />
              <button className="btn-cta full" onClick={generateSummary} disabled={summaryBusy} style={{ marginTop: 8 }}>
                {summaryBusy && <span className="spinner" />}Generate Professional Summary
              </button>
            </div>
          </details>

          <hr />
          <button className="btn-cta full" onClick={() => printResume(previewHtml)}>
            ⬇ Download Resume PDF
          </button>
        </div>

        {/* RIGHT: preview + audit */}
        <div>
          <div className="tabs">
            <button
              className={`tab ${rightTab === "preview" ? "active" : ""}`}
              onClick={() => setRightTab("preview")}
            >
              📄 Preview & Download
            </button>
            <button
              className={`tab ${rightTab === "audit" ? "active" : ""}`}
              onClick={() => setRightTab("audit")}
            >
              🎯 ATS Keyword Audit
            </button>
          </div>

          {rightTab === "preview" ? (
            <div>
              <label className="field-label">Template Style</label>
              <select
                value={templateId}
                onChange={(e) => setTemplateId(e.target.value as TemplateId)}
              >
                {(Object.keys(TEMPLATE_OPTIONS) as TemplateId[]).map((t) => (
                  <option key={t} value={t}>
                    {TEMPLATE_OPTIONS[t]}
                  </option>
                ))}
              </select>
              <div style={{ margin: "12px 0" }}>
                <button className="primary full" onClick={() => printResume(previewHtml)}>
                  🖨 Download ATS-Optimized PDF ({fileName})
                </button>
              </div>
              <ResumePreview html={previewHtml} />
            </div>
          ) : (
            <AtsAudit report={report} />
          )}
        </div>
      </div>
    </div>
  );
}
