// components/InterviewPrepGuide.tsx
// Renders a resume-specific interview preparation guide generated by the AI.
"use client";

import { useState } from "react";
import type { Resume } from "@/lib/types";
import { getAccessToken } from "@/lib/supabaseClient";

interface Props {
  resume: Resume;
  targetRole: string;
}

interface ImportantPrepQuestion {
  question: string;
  why_interviewer_may_ask: string;
  resume_connection: string;
  best_interview_answer: string;
  likely_follow_up_question: string;
  suggested_follow_up_answer: string;
  mistake_to_avoid: string;
}

interface LineByLinePrepQuestion {
  resume_statement: string;
  interview_question: string;
  practical_answer: string;
  cross_question: string;
  cross_question_answer: string;
}

interface ProjectDeepDive {
  project_name: string;
  overview: string;
  questions: Array<{
    question: string;
    answer: string;
    follow_up_question: string;
    follow_up_answer: string;
  }>;
}

interface SkillPrepSection {
  skill: string;
  questions: Array<{
    level: string;
    question: string;
    answer: string;
    exercise: string;
  }>;
}

interface SimpleQuestionAnswer {
  question: string;
  answer: string;
}

interface InterviewPrepGuideResult {
  risk_analysis: {
    strongest_resume_areas: string[];
    weakest_or_least_defendable_areas: string[];
    claims_likely_to_be_challenged: string[];
    missing_details_to_prepare: string[];
  };
  introductions: {
    thirty_second: string;
    sixty_to_ninety_second: string;
    walk_me_through_resume: string;
  };
  most_important_questions: ImportantPrepQuestion[];
  line_by_line_questions: LineByLinePrepQuestion[];
  project_deep_dives: ProjectDeepDive[];
  technical_skill_questions: SkillPrepSection[];
  workplace_scenarios: Array<{ scenario: string; answer: string }>;
  behavioral_hr_questions: SimpleQuestionAnswer[];
  rapid_fire: SimpleQuestionAnswer[];
  cross_questioning_round: Array<{ question: string; safe_response: string }>;
  missing_information: Array<{ item: string; question: string }>;
  final_preparation_sheet: {
    top_answers_to_memorise: string[];
    technical_concepts_to_revise: string[];
    project_stories_to_prepare: string[];
    weak_areas_to_handle: string[];
    interviewer_follow_up_questions: string[];
    one_day_revision_plan: string[];
    final_confidence_checklist: string[];
  };
  api_used: boolean;
  api_error: string | null;
}

function buildExperienceText(resume: Resume): string {
  return (resume.experience || [])
    .map((e) => {
      const header = `${e.role || "Role"} at ${e.company || "Company"} (${e.startDate || ""} to ${e.endDate || ""})`;
      const bullets = (e.bullets || []).filter(Boolean).map((b) => `- ${b}`).join("\n");
      return `${header}\n${bullets}`;
    })
    .join("\n\n");
}

function buildProjectsText(resume: Resume): string {
  return (resume.projects || [])
    .filter((p) => p.name || p.description || p.tech)
    .map((p) => `${p.name || "Project"}${p.tech ? ` | Tech: ${p.tech}` : ""}${p.link ? ` | Link: ${p.link}` : ""}\n${p.description || ""}`)
    .join("\n\n");
}

function buildSkillsText(resume: Resume): string {
  return (resume.skills || [])
    .filter((s) => s.category || s.list)
    .map((s) => `${s.category || "Skills"}: ${s.list || ""}`)
    .join("\n");
}

function buildEducationText(resume: Resume): string {
  return (resume.education || [])
    .filter((e) => e.degree || e.school || e.details)
    .map((e) => [e.degree, e.school, e.location, e.date, e.details].filter(Boolean).join(" | "))
    .join("\n");
}

function buildCertificationsText(resume: Resume): string {
  return (resume.certifications || [])
    .filter((c) => c.name || c.issuer)
    .map((c) => [c.name, c.issuer, c.date].filter(Boolean).join(" | "))
    .join("\n");
}

function TextList({ items }: { items?: string[] }) {
  const clean = (items || []).filter(Boolean);
  if (!clean.length) return <p className="muted" style={{ margin: 0 }}>No items returned.</p>;
  return (
    <ul style={{ margin: 0, paddingLeft: 18 }}>
      {clean.map((item, i) => <li key={`${item}-${i}`} style={{ marginBottom: 6 }}>{item}</li>)}
    </ul>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <details className="expander" open={title === "Introductions" || title === "Most Important Questions"}>
      <summary>{title}</summary>
      <div className="expander-body">{children}</div>
    </details>
  );
}

function QAItem({ q, a, extra }: { q: string; a: string; extra?: React.ReactNode }) {
  return (
    <details className="expander" style={{ marginBottom: 10 }}>
      <summary>{q || "Question"}</summary>
      <div className="expander-body">
        {a && <p style={{ margin: "0 0 10px", whiteSpace: "pre-wrap" }}>{a}</p>}
        {extra}
      </div>
    </details>
  );
}

export default function InterviewPrepGuide({ resume, targetRole }: Props) {
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<InterviewPrepGuideResult | null>(null);

  const hasEnoughData =
    Boolean(resume.summary?.trim()) ||
    (resume.experience || []).some((e) => e.company || e.role || e.bullets?.some(Boolean)) ||
    (resume.projects || []).some((p) => p.name || p.description);

  const generate = async () => {
    setBusy(true);
    setResult(null);
    try {
      const token = await getAccessToken();
      const res = await fetch("/api/generate-prep-guide", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          full_name: resume.personal?.fullName || "",
          target_role: targetRole,
          headline: resume.personal?.headline || "",
          summary: resume.summary || "",
          experience_text: buildExperienceText(resume),
          projects_text: buildProjectsText(resume),
          skills_text: buildSkillsText(resume),
          education_text: buildEducationText(resume),
          certifications_text: buildCertificationsText(resume),
        }),
      });
      const data = await res.json() as InterviewPrepGuideResult;
      setResult(data);
    } catch (e) {
      setResult({
        risk_analysis: {
          strongest_resume_areas: [],
          weakest_or_least_defendable_areas: [],
          claims_likely_to_be_challenged: [],
          missing_details_to_prepare: [],
        },
        introductions: { thirty_second: "", sixty_to_ninety_second: "", walk_me_through_resume: "" },
        most_important_questions: [],
        line_by_line_questions: [],
        project_deep_dives: [],
        technical_skill_questions: [],
        workplace_scenarios: [],
        behavioral_hr_questions: [],
        rapid_fire: [],
        cross_questioning_round: [],
        missing_information: [],
        final_preparation_sheet: {
          top_answers_to_memorise: [],
          technical_concepts_to_revise: [],
          project_stories_to_prepare: [],
          weak_areas_to_handle: [],
          interviewer_follow_up_questions: [],
          one_day_revision_plan: [],
          final_confidence_checklist: [],
        },
        api_used: false,
        api_error: e instanceof Error ? e.message : String(e),
      });
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="panel" style={{ marginBottom: 24 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 14, flexWrap: "wrap" }}>
        <div>
          <h3 style={{ margin: 0 }}>Resume-Specific Interview Questions</h3>
          <p className="caption" style={{ margin: "4px 0 0" }}>
            Generates questions, answers, cross-questions, weak areas, and revision notes from this resume.
          </p>
        </div>
        <button
          className="btn-cta"
          onClick={generate}
          disabled={busy || !hasEnoughData}
          title={!hasEnoughData ? "Add resume summary, experience, or a project first" : undefined}
        >
          {busy && <span className="spinner" />}
          {result ? "Regenerate Prep Guide" : "Generate Prep Guide"}
        </button>
      </div>

      {!hasEnoughData && (
        <div className="alert alert-warning" style={{ marginTop: 14 }}>
          Add resume summary, experience, or project details first. The guide is built directly from resume content.
        </div>
      )}

      {result?.api_error && (
        <div className={`alert alert-${result.api_used ? "warning" : "error"}`} style={{ marginTop: 14 }}>
          {result.api_error}
        </div>
      )}

      {result && (
        <div style={{ marginTop: 18 }}>
          <Section title="Risk Analysis">
            <div className="grid-2">
              <div>
                <strong>Strongest areas</strong>
                <TextList items={result.risk_analysis.strongest_resume_areas} />
              </div>
              <div>
                <strong>Weakest areas</strong>
                <TextList items={result.risk_analysis.weakest_or_least_defendable_areas} />
              </div>
              <div>
                <strong>Likely challenges</strong>
                <TextList items={result.risk_analysis.claims_likely_to_be_challenged} />
              </div>
              <div>
                <strong>Missing details</strong>
                <TextList items={result.risk_analysis.missing_details_to_prepare} />
              </div>
            </div>
          </Section>

          <Section title="Introductions">
            {result.introductions.thirty_second && (
              <>
                <strong>30-second answer</strong>
                <p style={{ whiteSpace: "pre-wrap" }}>{result.introductions.thirty_second}</p>
              </>
            )}
            {result.introductions.sixty_to_ninety_second && (
              <>
                <strong>60-90-second answer</strong>
                <p style={{ whiteSpace: "pre-wrap" }}>{result.introductions.sixty_to_ninety_second}</p>
              </>
            )}
            {result.introductions.walk_me_through_resume && (
              <>
                <strong>Walk me through your resume</strong>
                <p style={{ marginBottom: 0, whiteSpace: "pre-wrap" }}>{result.introductions.walk_me_through_resume}</p>
              </>
            )}
          </Section>

          <Section title="Most Important Questions">
            {result.most_important_questions.map((item, i) => (
              <QAItem
                key={`${item.question}-${i}`}
                q={`Q${i + 1}: ${item.question}`}
                a={item.best_interview_answer}
                extra={(
                  <div style={{ display: "grid", gap: 8 }}>
                    {item.why_interviewer_may_ask && <p style={{ margin: 0 }}><strong>Why asked:</strong> {item.why_interviewer_may_ask}</p>}
                    {item.resume_connection && <p style={{ margin: 0 }}><strong>Resume connection:</strong> {item.resume_connection}</p>}
                    {item.likely_follow_up_question && <p style={{ margin: 0 }}><strong>Follow-up:</strong> {item.likely_follow_up_question}</p>}
                    {item.suggested_follow_up_answer && <p style={{ margin: 0 }}><strong>Follow-up answer:</strong> {item.suggested_follow_up_answer}</p>}
                    {item.mistake_to_avoid && <p style={{ margin: 0 }}><strong>Mistake to avoid:</strong> {item.mistake_to_avoid}</p>}
                  </div>
                )}
              />
            ))}
          </Section>

          <Section title="Resume Line-by-Line Questions">
            {result.line_by_line_questions.map((item, i) => (
              <QAItem
                key={`${item.resume_statement}-${i}`}
                q={item.interview_question}
                a={item.practical_answer}
                extra={(
                  <>
                    {item.resume_statement && <p><strong>Resume statement:</strong> {item.resume_statement}</p>}
                    {item.cross_question && <p><strong>Cross-question:</strong> {item.cross_question}</p>}
                    {item.cross_question_answer && <p style={{ marginBottom: 0 }}><strong>Safe answer:</strong> {item.cross_question_answer}</p>}
                  </>
                )}
              />
            ))}
          </Section>

          <Section title="Project Deep Dives">
            {result.project_deep_dives.map((project, i) => (
              <div key={`${project.project_name}-${i}`} style={{ marginBottom: 16 }}>
                <h4>{project.project_name || `Project ${i + 1}`}</h4>
                {project.overview && <p>{project.overview}</p>}
                {project.questions.map((item, qi) => (
                  <QAItem
                    key={`${item.question}-${qi}`}
                    q={item.question}
                    a={item.answer}
                    extra={(
                      <>
                        {item.follow_up_question && <p><strong>Follow-up:</strong> {item.follow_up_question}</p>}
                        {item.follow_up_answer && <p style={{ marginBottom: 0 }}><strong>Follow-up answer:</strong> {item.follow_up_answer}</p>}
                      </>
                    )}
                  />
                ))}
              </div>
            ))}
          </Section>

          <Section title="Technical Skill Questions">
            {result.technical_skill_questions.map((skill, i) => (
              <div key={`${skill.skill}-${i}`} style={{ marginBottom: 16 }}>
                <h4>{skill.skill || `Skill ${i + 1}`}</h4>
                {skill.questions.map((item, qi) => (
                  <QAItem
                    key={`${item.question}-${qi}`}
                    q={`${item.level ? `${item.level}: ` : ""}${item.question}`}
                    a={item.answer}
                    extra={item.exercise ? <p style={{ marginBottom: 0 }}><strong>Exercise:</strong> {item.exercise}</p> : undefined}
                  />
                ))}
              </div>
            ))}
          </Section>

          <Section title="Workplace Scenarios">
            {result.workplace_scenarios.map((item, i) => <QAItem key={`${item.scenario}-${i}`} q={item.scenario} a={item.answer} />)}
          </Section>

          <Section title="Behavioural and HR Questions">
            {result.behavioral_hr_questions.map((item, i) => <QAItem key={`${item.question}-${i}`} q={item.question} a={item.answer} />)}
          </Section>

          <Section title="Rapid-Fire Round">
            {result.rapid_fire.map((item, i) => <QAItem key={`${item.question}-${i}`} q={item.question} a={item.answer} />)}
          </Section>

          <Section title="Strict Cross-Questioning">
            {result.cross_questioning_round.map((item, i) => (
              <QAItem key={`${item.question}-${i}`} q={item.question} a={item.safe_response} />
            ))}
          </Section>

          <Section title="Missing Information">
            {result.missing_information.map((item, i) => (
              <p key={`${item.item}-${i}`}><strong>{item.item || "Missing detail"}:</strong> {item.question}</p>
            ))}
          </Section>

          <Section title="Final Preparation Sheet">
            <div className="grid-2">
              <div><strong>Answers to memorise</strong><TextList items={result.final_preparation_sheet.top_answers_to_memorise} /></div>
              <div><strong>Concepts to revise</strong><TextList items={result.final_preparation_sheet.technical_concepts_to_revise} /></div>
              <div><strong>Project stories</strong><TextList items={result.final_preparation_sheet.project_stories_to_prepare} /></div>
              <div><strong>Weak areas</strong><TextList items={result.final_preparation_sheet.weak_areas_to_handle} /></div>
              <div><strong>Follow-up questions</strong><TextList items={result.final_preparation_sheet.interviewer_follow_up_questions} /></div>
              <div><strong>One-day plan</strong><TextList items={result.final_preparation_sheet.one_day_revision_plan} /></div>
              <div><strong>Confidence checklist</strong><TextList items={result.final_preparation_sheet.final_confidence_checklist} /></div>
            </div>
          </Section>
        </div>
      )}
    </div>
  );
}
